# [作業目標]

1. [簡答題] 請問下列四種不同的 DataFrame 選取結果有什麼差異？

```
df.loc[ '2013-01-01', 'A'] 
df.loc[ '2013-01-01', ['A', 'B'] ] 
df.loc[ '2013-01-01':'2013-01-02', 'A' ] 
df.loc[ '2013-01-01':'2013-01-05', 'A':'C'] 
```


2. 請根據提供的資料，選擇出下列的要求：

```
# - select the first 3 rows.
# - select the odd rows. (index = 1, 3, 5)
# - select the last 2 columns.
# - select the even columns. (index = 0, 2, 4)
```

3. 請根據提供的資料，選擇出下列的要求：

```
# - 1. filtered by first column > 20?
# - 2. filtered by first column + second column > 50
# - 3. filtered by first column < 30 or second column > 30
# - 4. filtered by total sum of row > 100
```

# 作業

### 1. [簡答題] 請問下列四種不同的 DataFrame 選取結果有什麼差異？

```
df.loc[ '2013-01-01', 'A'] 
df.loc[ '2013-01-01', ['A', 'B'] ] 
df.loc[ '2013-01-01':'2013-01-02', 'A' ] 
df.loc[ '2013-01-01':'2013-01-05', 'A':'C'] 
```

```
df.loc[ '2013-01-01', 'A']                     # 取得 2013-01-01 這列的 A 欄資料
df.loc[ '2013-01-01', ['A', 'B'] ]             # 取得 2013-01-01 這列的 A, B 二欄資料
df.loc[ '2013-01-01':'2013-01-02', 'A' ]       # 取得 2013-01-01 到 2013-01-02 這幾列的 A 欄資料
df.loc[ '2013-01-01':'2013-01-05', 'A':'C']    # 取得 2013-01-01 到 2013-01-02 這幾列的 A 到 C 欄資料
```

### 2. 請根據提供的資料，選擇出下列的要求：

```
# - select the first 3 rows.
# - select the odd rows. (index = 1, 3, 5)
# - select the last 2 columns.
# - select the even columns. (index = 0, 2, 4)
```

In [4]:
# 記得先 Import 正確的套件
import pandas as pd
import numpy as np

In [12]:
df = pd.DataFrame(np.random.randn(6,3),columns=['col1','col2','col3'])
df

       col1      col2      col3
0  1.095123  0.818793  1.859401
1 -1.294630 -0.004502  0.254181
2  0.995658 -0.577837  0.386256
3 -1.030283  0.071718  1.194046
4  0.165025 -1.851229  0.572968
5  1.491526  1.160980 -0.875742

In [13]:
print(df[0:3])
print(df[1::2])
print(df.iloc[:, -2:])
print(df.iloc[:, ::2])

       col1      col2      col3
0  1.095123  0.818793  1.859401
1 -1.294630 -0.004502  0.254181
2  0.995658 -0.577837  0.386256
       col1      col2      col3
1 -1.294630 -0.004502  0.254181
3 -1.030283  0.071718  1.194046
5  1.491526  1.160980 -0.875742
       col2      col3
0  0.818793  1.859401
1 -0.004502  0.254181
2 -0.577837  0.386256
3  0.071718  1.194046
4 -1.851229  0.572968
5  1.160980 -0.875742
       col1      col3
0  1.095123  1.859401
1 -1.294630  0.254181
2  0.995658  0.386256
3 -1.030283  1.194046
4  0.165025  0.572968
5  1.491526 -0.875742

### 3. 請根據提供的資料，選擇出下列的要求：

```
# - 1. filtered by first column > 20?
# - 2. filtered by first column + second column > 50
# - 3. filtered by first column < 30 or second column > 30
# - 4. filtered by total sum of row > 100
```

In [14]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
df

     0   1   2   3
0   38  27  29  13
1   32  33  11  39
2   16  12  26  39
3   15  19  11  34
4   29  15  18  17
5   15  20  10  30
6   30  16  10  24
7   26  29  16  35
8   11  27  35  38
9   33  38  17  37
10  11  35  14  32
11  29  27  19  28
12  13  13  24  30
13  11  21  18  11
14  34  38  24  27

In [17]:
print(df[df[0] > 20])

     0   1   2   3
0   38  27  29  13
1   32  33  11  39
4   29  15  18  17
6   30  16  10  24
7   26  29  16  35
9   33  38  17  37
11  29  27  19  28
14  34  38  24  27

In [18]:
print(df[(df[0] + df[1]) > 50])

     0   1   2   3
0   38  27  29  13
1   32  33  11  39
7   26  29  16  35
9   33  38  17  37
11  29  27  19  28
14  34  38  24  27

In [19]:
print(df[(df[0] < 30) | (df[1] > 30)])

     0   1   2   3
1   32  33  11  39
2   16  12  26  39
3   15  19  11  34
4   29  15  18  17
5   15  20  10  30
7   26  29  16  35
8   11  27  35  38
9   33  38  17  37
10  11  35  14  32
11  29  27  19  28
12  13  13  24  30
13  11  21  18  11
14  34  38  24  27

In [21]:
print(df[df.sum(axis=1) > 100])

     0   1   2   3
0   38  27  29  13
1   32  33  11  39
7   26  29  16  35
8   11  27  35  38
9   33  38  17  37
11  29  27  19  28
14  34  38  24  27